# docker-compose for kafka broker with ssl enabled but no strict ssl check for clients

### Make sure to set the following variable in .env or as environment variable
#KAFKA_HOST_NAME=kafka.broker.dev.local

### Make sure to add the following files to /docker_volume/kafka/ssl_secrets folders
#keystore_pwd1.txt
#truststore_pwd1.txt
#broker.keystore.p12
#broker.truststore.p12

### Example client configuration(eg: client-with-ssl.properties) to connect to kafka broker
#security.protocol=SSL

version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,SSL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,SSL://${KAFKA_HOST_NAME}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ### Debug options ###
      #KAFKA_OPTS: "-Djavax.net.debug=ssl:handshake" #to show SSL handshake info in log
      ### SSL config ###
      KAFKA_SSL_KEYSTORE_FILENAME: broker.keystore.p12
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_pwd1.txt
      KAFKA_SSL_KEY_CREDENTIALS: keystore_pwd1.txt
      KAFKA_SSL_TRUSTSTORE_FILENAME: broker.truststore.p12
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore_pwd1.txt
      KAFKA_SSL_CLIENT_AUTH: 'none' #if its set 'none', then client's doesn't need to valid its certificate to connect with broker
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      ## SEEMS REDUNDANT - if not set, inter broker communication is failing
#      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/broker.keystore.p12
#      KAFKA_SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
#      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/broker.truststore.p12
#      KAFKA_SSL_TRUSTSTORE_PASSWORD: ${SSL_TRUSTSTORE_PASSWORD}
    volumes:
      - ./docker_volume/kafka/ssl_secrets:/etc/kafka/secrets:ro  # Ensure this points to the directory with your keystore and truststore

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181