# This docker-compose is for TESTING PURPOSE only
# docker-compose for kafka broker with ssl enabled and client's need a valid certificate to connect to broker


### example client configuration(eg: client-ssl.properties) to connect to kafka with ssl and non-auth enabled
#security.protocol=SSL

version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093 # SASL_SSL listener
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,SSL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,SSL://${HOST_NAME}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ### Debug options ###
      KAFKA_OPTS: "-Djavax.net.debug=ssl:handshake" #to show SSL handshake info in log
      ### SSL config ###
      KAFKA_SSL_KEYSTORE_FILENAME: keystore.p12
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore_pwd1.txt
      KAFKA_SSL_KEY_CREDENTIALS: keystore_pwd1.txt
      KAFKA_SSL_TRUSTSTORE_FILENAME: truststore.p12
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore_pwd1.txt
      KAFKA_SSL_CLIENT_AUTH: 'none' #if its set 'none', then client's doesn't need to valid its certificate to connect with broker
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      ## SEEMS REDUNDANT
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.p12
      KAFKA_SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.p12
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ${SSL_TRUSTSTORE_PASSWORD}
    volumes:
      - ./secrets:/etc/kafka/secrets:ro  # Ensure this points to the directory with your keystore and truststore

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181