---
#server:
#  port: 8882
spring:
  application:
    name: app2-development-prototype-kafka-consumer
  kafka:
    bootstrap-servers: kafka.broker.local:9093
logging:
  level:
    org:
      springframework:
        kafka: WARN
# custom properties
consumers:
  string_consumer:
    topics: app2.development.prototype.kafka.dev.string.event.v1
    groupId: app2.development.prototype.kafka-dev-kafka-consumer-group_1
  batch_string_consumer:
    topics: app2.development.prototype.kafka.dev.string.event.v1
    groupId: app2.development.prototype.kafka-dev-kafka-consumer-group_2
    containerFactory: batchContainerFactory
  message_consumer:
    topics: app2.development.prototype.kafka.dev.message.event.v1
    groupId: app2.development.prototype.kafka-dev-kafka-consumer-group_3
    containerFactory: messageContainerFactory